name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    types:
      - closed
    branches:
      - dev

jobs:
  

  deploy:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: deep3ssasAPP
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: mdakk072/deep3ssas:latest

