name: CI

on:
  push:
    branches:
      - master

jobs:

  deploy:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    

    - name: Build and push Docker image for data_handler
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: ./docker/data_handler/Dockerfile
        push: true
        tags: mdakk072/deep3ssasapi:latest


    - name: Build and push Docker image for web_app
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: ./docker/web_app/Dockerfile

        push: true
        tags: mdakk072/deep3ssasapp:latest
    
    - name: Deploy data_handler to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: deep3ssasDataHandler
        publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
        images: mdakk072/deep3ssasapi:latest
    - name: Deploy web_app to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: deep3ssasWebApp
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: mdakk072/deep3ssasapp:latest
